// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cFB.Data.EFs;

namespace cFB.Data.Migrations
{
    [DbContext(typeof(cFBDbContext))]
    [Migration("20220107070942_Intal")]
    partial class Intal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cFB.Data.Entites.AdministrativeDivision", b =>
                {
                    b.Property<string>("AdministrativeDivisionId")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Addrees")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AdministrativeDivisionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("CheckPass")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumberPhone")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 1, 7, 14, 9, 41, 624, DateTimeKind.Local).AddTicks(7356));

                    b.HasKey("AdministrativeDivisionId");

                    b.HasIndex("ManagerId");

                    b.ToTable("AdministrativeDivision");

                    b.HasData(
                        new
                        {
                            AdministrativeDivisionId = "86C1",
                            Addrees = "158 Đặng Văn Lãnh, TP Phan Thiết",
                            AdministrativeDivisionName = "Thành phố Phan Thiết",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523822694",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B1",
                            Addrees = "Đường 17/4, thị trấn Liên Hương, huyện Tuy Phong",
                            AdministrativeDivisionName = "Huyện Tuy Phong",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523850163",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B2",
                            Addrees = "17 Lê Hồng Phong, khu phố Xuân An 2, thị trấn Chợ Lầu, huyện Bắc Bình",
                            AdministrativeDivisionName = "Huyện Bắc Bình",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523860133",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B3",
                            Addrees = "Khu phố Lâm Hòa, thị trấn Ma Lâm, huyện Hàm Thuận Bắc",
                            AdministrativeDivisionName = "Huyện Hàm Thuận Bắc",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523865113",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B4",
                            Addrees = "14 Trần phú, thị trấn Thuận Nam, huyện Hàm Thuận Nam",
                            AdministrativeDivisionName = "Huyện Hàm Thuận Nam",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523867113",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B5",
                            Addrees = "Khu phố 2, Thị trấn Tân Nghĩa, huyện Hàm Tân",
                            AdministrativeDivisionName = "Huyện Hàm Tân",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523876100",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B6",
                            Addrees = "02 Ngô Gia Tự, phường Tân An, thị xã La Gi",
                            AdministrativeDivisionName = "Thị xã La Gi",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523871988",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B7",
                            Addrees = "449 Trần Hưng Đạo, khu phố Lạc Hóa 1, thị trấn Lạc Tánh, huyện Tánh Linh",
                            AdministrativeDivisionName = "Huyện Tánh Linh",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "0794201396",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B8",
                            Addrees = "Thôn 2, xã Nam Chính, huyện Đức Linh",
                            AdministrativeDivisionName = "Huyện Đức Linh",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523882113",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "86B9",
                            Addrees = "239 Hùng Vương, thôn Quý Thanh, xã Ngũ Phụng, huyện Phú Quý",
                            AdministrativeDivisionName = "Huyện Phú Quý",
                            CheckPass = false,
                            ManagerId = "User",
                            NumberPhone = "02523767434",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdministrativeDivisionId = "Admin",
                            Addrees = "239 Hùng Vương, thôn Quý Thanh, xã Ngũ Phụng, huyện Phú Quý",
                            AdministrativeDivisionName = "Admin",
                            CheckPass = false,
                            ManagerId = "Admin",
                            NumberPhone = "02523767434",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            TimeOnline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("cFB.Data.Entites.FaceBookType", b =>
                {
                    b.Property<string>("FaceBookTypeId")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaceBookTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FaceBookTypeId");

                    b.ToTable("FaceBookType");

                    b.HasData(
                        new
                        {
                            FaceBookTypeId = "CGR",
                            Description = "Group kín, nơi mọi người có thể xem tên nhóm và thành viên, nhưng không xem được nội dung của nhóm.",
                            FaceBookTypeName = "Nhóm Kín"
                        },
                        new
                        {
                            FaceBookTypeId = "GR",
                            Description = "Group công khai, nơi mọi người có thể xem tất cả nội dung và các thành viên.",
                            FaceBookTypeName = "Nhóm Công Khai"
                        },
                        new
                        {
                            FaceBookTypeId = "PAGE",
                            Description = "Trang công khai",
                            FaceBookTypeName = "Trang"
                        },
                        new
                        {
                            FaceBookTypeId = "USER",
                            Description = "Tài khoản của người dùng thông thường",
                            FaceBookTypeName = "Cá nhân"
                        });
                });

            modelBuilder.Entity("cFB.Data.Entites.History", b =>
                {
                    b.Property<string>("AdministrativeDivisionId")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<string>("StatusHistory")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("AdministrativeDivisionId", "Time");

                    b.ToTable("History");
                });

            modelBuilder.Entity("cFB.Data.Entites.HistoryClient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdministrativeDivisionID")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameMachine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 1, 7, 14, 9, 41, 648, DateTimeKind.Local).AddTicks(9328));

                    b.HasKey("ID");

                    b.HasIndex("AdministrativeDivisionID");

                    b.ToTable("HistoryClient");
                });

            modelBuilder.Entity("cFB.Data.Entites.NewsLabel", b =>
                {
                    b.Property<string>("NewsLabelId")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("NewsLabelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NewsLabelId");

                    b.ToTable("NewsLabel");

                    b.HasData(
                        new
                        {
                            NewsLabelId = "AN",
                            NewsLabelName = "Âm nhạc"
                        },
                        new
                        {
                            NewsLabelId = "ANQG",
                            NewsLabelName = "An ninh quốc gia"
                        },
                        new
                        {
                            NewsLabelId = "ANTT",
                            NewsLabelName = "An ninh trật tự"
                        },
                        new
                        {
                            NewsLabelId = "AT",
                            NewsLabelName = "Ẩm thực"
                        },
                        new
                        {
                            NewsLabelId = "CN",
                            NewsLabelName = "Công nghệ"
                        },
                        new
                        {
                            NewsLabelId = "DL",
                            NewsLabelName = "Du lịch"
                        },
                        new
                        {
                            NewsLabelId = "GD",
                            NewsLabelName = "Giáo dục"
                        },
                        new
                        {
                            NewsLabelId = "GT",
                            NewsLabelName = "Giải trí"
                        },
                        new
                        {
                            NewsLabelId = "KD",
                            NewsLabelName = "Kinh Doanh"
                        },
                        new
                        {
                            NewsLabelId = "PA",
                            NewsLabelName = "Phim ảnh"
                        },
                        new
                        {
                            NewsLabelId = "PL",
                            NewsLabelName = "Pháp luật"
                        },
                        new
                        {
                            NewsLabelId = "SK",
                            NewsLabelName = "Sức khỏe"
                        },
                        new
                        {
                            NewsLabelId = "ST",
                            NewsLabelName = "Sống trẻ"
                        },
                        new
                        {
                            NewsLabelId = "TG",
                            NewsLabelName = "Thế giới"
                        },
                        new
                        {
                            NewsLabelId = "TS",
                            NewsLabelName = "Thời sự"
                        },
                        new
                        {
                            NewsLabelId = "TTH",
                            NewsLabelName = "Thể thao"
                        },
                        new
                        {
                            NewsLabelId = "TTR",
                            NewsLabelName = "Thời trang"
                        },
                        new
                        {
                            NewsLabelId = "XB",
                            NewsLabelName = "Xuất bản"
                        },
                        new
                        {
                            NewsLabelId = "XE",
                            NewsLabelName = "Xe"
                        });
                });

            modelBuilder.Entity("cFB.Data.Entites.Post", b =>
                {
                    b.Property<string>("PostId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdministrativeDivisionId")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CrawledTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 1, 7, 14, 9, 41, 636, DateTimeKind.Local).AddTicks(988));

                    b.Property<string>("FaceBookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FilePDF")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsLabelId")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("PostContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Report")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SentimentLabelId")
                        .HasColumnType("varchar(8)");

                    b.Property<int>("TotalComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalShare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UploadTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 1, 7, 14, 9, 41, 636, DateTimeKind.Local).AddTicks(581));

                    b.Property<string>("UserUrl")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("PostId");

                    b.HasIndex("AdministrativeDivisionId");

                    b.HasIndex("FaceBookId");

                    b.HasIndex("NewsLabelId");

                    b.HasIndex("SentimentLabelId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("cFB.Data.Entites.Report", b =>
                {
                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdministrativeDivisionId")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DateReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 1, 7, 14, 9, 41, 646, DateTimeKind.Local).AddTicks(7032));

                    b.Property<string>("FileReport")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ReportId");

                    b.HasIndex("AdministrativeDivisionId");

                    b.HasIndex("PostId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("cFB.Data.Entites.RoleManager", b =>
                {
                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerId");

                    b.ToTable("RoleManager");

                    b.HasData(
                        new
                        {
                            ManagerId = "Admin",
                            ManagerName = "Nơi quản lý cao nhất"
                        },
                        new
                        {
                            ManagerId = "User",
                            ManagerName = "Các địa phương sử dụng"
                        });
                });

            modelBuilder.Entity("cFB.Data.Entites.SentimentLabel", b =>
                {
                    b.Property<string>("SentimentLabelId")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("SentimentLabelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SentimentLabelId");

                    b.ToTable("SentimentLabel");

                    b.HasData(
                        new
                        {
                            SentimentLabelId = "NEG",
                            SentimentLabelName = "Tiêu cực"
                        },
                        new
                        {
                            SentimentLabelId = "NEU",
                            SentimentLabelName = "Bình thường"
                        },
                        new
                        {
                            SentimentLabelId = "POS",
                            SentimentLabelName = "Tích cực"
                        });
                });

            modelBuilder.Entity("cFB.Data.Entites.WatchList", b =>
                {
                    b.Property<string>("FaceBookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdministrativeDivisionId")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FaceBookName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FaceBookTypeId")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("FaceBookUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("FaceBookId");

                    b.HasIndex("AdministrativeDivisionId");

                    b.HasIndex("FaceBookTypeId");

                    b.ToTable("WatchList");

                    b.HasData(
                        new
                        {
                            FaceBookId = "1648199831900386Admin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Triệt Hạ Bò Đỏ",
                            FaceBookTypeId = "GR",
                            FaceBookUrl = "https://www.facebook.com/groups/1648199831900386",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "1752456318197543Admin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Xây Dựng Đảng",
                            FaceBookTypeId = "GR",
                            FaceBookUrl = "https://www.facebook.com/groups/1752456318197543",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "187530275233978Admin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "BÀN LUẬN về KINH TẾ - CHÍNH TRỊ 2",
                            FaceBookTypeId = "GR",
                            FaceBookUrl = "https://www.facebook.com/groups/187530275233978",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "90trieunguoiAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "VIỆT NAM DÂN CHỦ",
                            FaceBookTypeId = "PAGE",
                            FaceBookUrl = "https://www.facebook.com/90trieunguoi",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "bao.luong.5011516Admin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Luong Quang Bao",
                            FaceBookTypeId = "USER",
                            FaceBookUrl = "https://www.facebook.com/bao.luong.5011516",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "BinhLuanVeDangCongSanAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Bình Luận Về Đảng Cộng Sản",
                            FaceBookTypeId = "PAGE",
                            FaceBookUrl = "https://www.facebook.com/BinhLuanVeDangCongSan",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "DuaLeo.Stand.up.comedianAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Dưa Leo - Stand up comedian",
                            FaceBookTypeId = "PAGE",
                            FaceBookUrl = "https://www.facebook.com/DuaLeo.Stand.up.comedian",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "HuyFreedomSaigonAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Huỳnh Quốc Huy (John Whale)",
                            FaceBookTypeId = "USER",
                            FaceBookUrl = "https://www.facebook.com/HuyFreedomSaigon",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "kinhtechinhtrixahoivnAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Bàn Luận về Kinh Tế - Chính Trị",
                            FaceBookTypeId = "GR",
                            FaceBookUrl = "https://www.facebook.com/groups/kinhtechinhtrixahoivn",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "lukhachAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Nguyen Huy Vu",
                            FaceBookTypeId = "USER",
                            FaceBookUrl = "https://www.facebook.com/lukhach",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "mothermushroomAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Mẹ Nấm",
                            FaceBookTypeId = "USER",
                            FaceBookUrl = "https://www.facebook.com/mothermushroom",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "nhabaocongdanAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Góc nhìn báo chí - Công dân",
                            FaceBookTypeId = "GR",
                            FaceBookUrl = "https://www.facebook.com/groups/nhabaocongdan",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "nhatkyyeunuoc1Admin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Nhật Ký Yêu Nước",
                            FaceBookTypeId = "PAGE",
                            FaceBookUrl = "https://www.facebook.com/nhatkyyeunuoc1",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "phapluatvacuocsong.vnAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Pháp luật & Cuộc sống",
                            FaceBookTypeId = "PAGE",
                            FaceBookUrl = "https://www.facebook.com/phapluatvacuocsong.vn",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "TamConXuyenDiepAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Tam Côn Xuyên Diệp",
                            FaceBookTypeId = "GR",
                            FaceBookUrl = "https://www.facebook.com/groups/TamConXuyenDiep",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "thong.luan.1Admin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Tập Hợp Dân Chủ Đa Nguyên",
                            FaceBookTypeId = "PAGE",
                            FaceBookUrl = "https://www.facebook.com/thong.luan.1",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "thuc.tranhuynhduyAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Trần Huỳnh Duy Thức",
                            FaceBookTypeId = "USER",
                            FaceBookUrl = "https://www.facebook.com/thuc.tranhuynhduy",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "vietnamconghoa123Admin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Việt Nam Cộng Hòa",
                            FaceBookTypeId = "PAGE",
                            FaceBookUrl = "https://www.facebook.com/vietnamconghoa123",
                            Status = 0
                        },
                        new
                        {
                            FaceBookId = "viettanAdmin",
                            AdministrativeDivisionId = "Admin",
                            FaceBookName = "Việt Tân",
                            FaceBookTypeId = "PAGE",
                            FaceBookUrl = "https://www.facebook.com/viettan",
                            Status = 0
                        });
                });

            modelBuilder.Entity("cFB.Data.Entites.AdministrativeDivision", b =>
                {
                    b.HasOne("cFB.Data.Entites.RoleManager", "RoleManager")
                        .WithMany("AdministrativeDivision")
                        .HasForeignKey("ManagerId");

                    b.Navigation("RoleManager");
                });

            modelBuilder.Entity("cFB.Data.Entites.History", b =>
                {
                    b.HasOne("cFB.Data.Entites.AdministrativeDivision", "AdministrativeDivisions")
                        .WithMany("Histories")
                        .HasForeignKey("AdministrativeDivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministrativeDivisions");
                });

            modelBuilder.Entity("cFB.Data.Entites.HistoryClient", b =>
                {
                    b.HasOne("cFB.Data.Entites.AdministrativeDivision", "AdministrativeDivisions")
                        .WithMany("HistoryClients")
                        .HasForeignKey("AdministrativeDivisionID");

                    b.Navigation("AdministrativeDivisions");
                });

            modelBuilder.Entity("cFB.Data.Entites.Post", b =>
                {
                    b.HasOne("cFB.Data.Entites.AdministrativeDivision", "AdministrativeDivisions")
                        .WithMany("Posts")
                        .HasForeignKey("AdministrativeDivisionId");

                    b.HasOne("cFB.Data.Entites.WatchList", "WatchList")
                        .WithMany("Posts")
                        .HasForeignKey("FaceBookId");

                    b.HasOne("cFB.Data.Entites.NewsLabel", "NewsLabel")
                        .WithMany("Posts")
                        .HasForeignKey("NewsLabelId");

                    b.HasOne("cFB.Data.Entites.SentimentLabel", "SentimentLabel")
                        .WithMany("Posts")
                        .HasForeignKey("SentimentLabelId");

                    b.Navigation("AdministrativeDivisions");

                    b.Navigation("NewsLabel");

                    b.Navigation("SentimentLabel");

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("cFB.Data.Entites.Report", b =>
                {
                    b.HasOne("cFB.Data.Entites.AdministrativeDivision", "AdministrativeDivision")
                        .WithMany("Reports")
                        .HasForeignKey("AdministrativeDivisionId");

                    b.HasOne("cFB.Data.Entites.Post", "Posts")
                        .WithMany("Reports")
                        .HasForeignKey("PostId");

                    b.Navigation("AdministrativeDivision");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("cFB.Data.Entites.WatchList", b =>
                {
                    b.HasOne("cFB.Data.Entites.AdministrativeDivision", "AdministrativeDivisions")
                        .WithMany("WatchLists")
                        .HasForeignKey("AdministrativeDivisionId");

                    b.HasOne("cFB.Data.Entites.FaceBookType", "FaceBookType")
                        .WithMany("WatchLists")
                        .HasForeignKey("FaceBookTypeId");

                    b.Navigation("AdministrativeDivisions");

                    b.Navigation("FaceBookType");
                });

            modelBuilder.Entity("cFB.Data.Entites.AdministrativeDivision", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("HistoryClients");

                    b.Navigation("Posts");

                    b.Navigation("Reports");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("cFB.Data.Entites.FaceBookType", b =>
                {
                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("cFB.Data.Entites.NewsLabel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("cFB.Data.Entites.Post", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("cFB.Data.Entites.RoleManager", b =>
                {
                    b.Navigation("AdministrativeDivision");
                });

            modelBuilder.Entity("cFB.Data.Entites.SentimentLabel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("cFB.Data.Entites.WatchList", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
